# Generated by Django 2.2.3 on 2019-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190829_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='rate',
            new_name='CCrate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Wrate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
