# Generated by Django 2.2.3 on 2020-11-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190910_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='BTCrate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='btc',
            field=models.BooleanField(default=False),
        ),
    ]
