services:
  backend:
    build:
      context: ./backend
    ports:
      - "8017:8017"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "3017:3017"
    depends_on:
      - backend
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

volumes:
  redis_data:
    driver: local