services:
  backend:
    build:
      context: ./backend
    ports:
      - "8017:8017"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3017:3017"
    depends_on:
      - backend
