export const USER_ADD = "USER_ADD";
export const USER_REMOVE = "USER_REMOVE";
export const USER_UPDATE = "USER_UPDATE";
export const USER_DEACTIVATE = "USER_DEACTIVATE";
export const USER_ACTIVATE = "USER_ACTIVATE";
export const TRANSACTION_ADD = "TRANSACTION_ADD";
export const TRANSACTION_REMOVE = "TRANSACTION_REMOVE";
export const TRANSACTION_UPDATE = "TRANSACTION_UPDATE";